// Code generated by entc, DO NOT EDIT.

package stardict

const (
	// Label holds the string label denoting the stardict type in the database.
	Label = "star_dict"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldWord holds the string denoting the word field in the database.
	FieldWord = "word"
	// FieldSw holds the string denoting the sw field in the database.
	FieldSw = "sw"
	// FieldPhonetic holds the string denoting the phonetic field in the database.
	FieldPhonetic = "phonetic"
	// FieldDefinition holds the string denoting the definition field in the database.
	FieldDefinition = "definition"
	// FieldTranslation holds the string denoting the translation field in the database.
	FieldTranslation = "translation"
	// FieldPos holds the string denoting the pos field in the database.
	FieldPos = "pos"
	// FieldCollins holds the string denoting the collins field in the database.
	FieldCollins = "collins"
	// FieldOxford holds the string denoting the oxford field in the database.
	FieldOxford = "oxford"
	// FieldTag holds the string denoting the tag field in the database.
	FieldTag = "tag"
	// FieldBnc holds the string denoting the bnc field in the database.
	FieldBnc = "bnc"
	// FieldFrq holds the string denoting the frq field in the database.
	FieldFrq = "frq"
	// FieldExchange holds the string denoting the exchange field in the database.
	FieldExchange = "exchange"
	// FieldDetail holds the string denoting the detail field in the database.
	FieldDetail = "detail"
	// FieldAudio holds the string denoting the audio field in the database.
	FieldAudio = "audio"
	// Table holds the table name of the stardict in the database.
	Table = "stardict"
)

// Columns holds all SQL columns for stardict fields.
var Columns = []string{
	FieldID,
	FieldWord,
	FieldSw,
	FieldPhonetic,
	FieldDefinition,
	FieldTranslation,
	FieldPos,
	FieldCollins,
	FieldOxford,
	FieldTag,
	FieldBnc,
	FieldFrq,
	FieldExchange,
	FieldDetail,
	FieldAudio,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// WordValidator is a validator for the "word" field. It is called by the builders before save.
	WordValidator func(string) error
	// SwValidator is a validator for the "sw" field. It is called by the builders before save.
	SwValidator func(string) error
	// DefaultPhonetic holds the default value on creation for the "phonetic" field.
	DefaultPhonetic string
	// DefaultDefinition holds the default value on creation for the "definition" field.
	DefaultDefinition string
	// DefaultTranslation holds the default value on creation for the "translation" field.
	DefaultTranslation string
	// DefaultPos holds the default value on creation for the "pos" field.
	DefaultPos string
	// DefaultCollins holds the default value on creation for the "collins" field.
	DefaultCollins int
	// DefaultOxford holds the default value on creation for the "oxford" field.
	DefaultOxford int
	// DefaultTag holds the default value on creation for the "tag" field.
	DefaultTag string
	// DefaultExchange holds the default value on creation for the "exchange" field.
	DefaultExchange string
	// DefaultDetail holds the default value on creation for the "detail" field.
	DefaultDetail string
	// DefaultAudio holds the default value on creation for the "audio" field.
	DefaultAudio string
)
