// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// WordsColumns holds the columns for the "words" table.
	WordsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "word", Type: field.TypeString, Unique: true},
		{Name: "explain", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "phonetic", Type: field.TypeString, Default: ""},
		{Name: "frequency", Type: field.TypeInt, Default: 0},
		{Name: "last_show_time", Type: field.TypeTime},
		{Name: "is_hide", Type: field.TypeBool, Default: false},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "delete_time", Type: field.TypeTime},
		{Name: "is_delete", Type: field.TypeBool, Default: false},
	}
	// WordsTable holds the schema information for the "words" table.
	WordsTable = &schema.Table{
		Name:       "words",
		Columns:    WordsColumns,
		PrimaryKey: []*schema.Column{WordsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		WordsTable,
	}
)

func init() {
}
