// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"
	"telegram-bot/internal/ent/predicate"
	"telegram-bot/internal/ent/stardict"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StarDictQuery is the builder for querying StarDict entities.
type StarDictQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.StarDict
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the StarDictQuery builder.
func (sdq *StarDictQuery) Where(ps ...predicate.StarDict) *StarDictQuery {
	sdq.predicates = append(sdq.predicates, ps...)
	return sdq
}

// Limit adds a limit step to the query.
func (sdq *StarDictQuery) Limit(limit int) *StarDictQuery {
	sdq.limit = &limit
	return sdq
}

// Offset adds an offset step to the query.
func (sdq *StarDictQuery) Offset(offset int) *StarDictQuery {
	sdq.offset = &offset
	return sdq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sdq *StarDictQuery) Unique(unique bool) *StarDictQuery {
	sdq.unique = &unique
	return sdq
}

// Order adds an order step to the query.
func (sdq *StarDictQuery) Order(o ...OrderFunc) *StarDictQuery {
	sdq.order = append(sdq.order, o...)
	return sdq
}

// First returns the first StarDict entity from the query.
// Returns a *NotFoundError when no StarDict was found.
func (sdq *StarDictQuery) First(ctx context.Context) (*StarDict, error) {
	nodes, err := sdq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{stardict.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sdq *StarDictQuery) FirstX(ctx context.Context) *StarDict {
	node, err := sdq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first StarDict ID from the query.
// Returns a *NotFoundError when no StarDict ID was found.
func (sdq *StarDictQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sdq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{stardict.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sdq *StarDictQuery) FirstIDX(ctx context.Context) int {
	id, err := sdq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single StarDict entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one StarDict entity is found.
// Returns a *NotFoundError when no StarDict entities are found.
func (sdq *StarDictQuery) Only(ctx context.Context) (*StarDict, error) {
	nodes, err := sdq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{stardict.Label}
	default:
		return nil, &NotSingularError{stardict.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sdq *StarDictQuery) OnlyX(ctx context.Context) *StarDict {
	node, err := sdq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only StarDict ID in the query.
// Returns a *NotSingularError when more than one StarDict ID is found.
// Returns a *NotFoundError when no entities are found.
func (sdq *StarDictQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sdq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{stardict.Label}
	default:
		err = &NotSingularError{stardict.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sdq *StarDictQuery) OnlyIDX(ctx context.Context) int {
	id, err := sdq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of StarDicts.
func (sdq *StarDictQuery) All(ctx context.Context) ([]*StarDict, error) {
	if err := sdq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return sdq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (sdq *StarDictQuery) AllX(ctx context.Context) []*StarDict {
	nodes, err := sdq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of StarDict IDs.
func (sdq *StarDictQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := sdq.Select(stardict.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sdq *StarDictQuery) IDsX(ctx context.Context) []int {
	ids, err := sdq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sdq *StarDictQuery) Count(ctx context.Context) (int, error) {
	if err := sdq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return sdq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (sdq *StarDictQuery) CountX(ctx context.Context) int {
	count, err := sdq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sdq *StarDictQuery) Exist(ctx context.Context) (bool, error) {
	if err := sdq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return sdq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (sdq *StarDictQuery) ExistX(ctx context.Context) bool {
	exist, err := sdq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the StarDictQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sdq *StarDictQuery) Clone() *StarDictQuery {
	if sdq == nil {
		return nil
	}
	return &StarDictQuery{
		config:     sdq.config,
		limit:      sdq.limit,
		offset:     sdq.offset,
		order:      append([]OrderFunc{}, sdq.order...),
		predicates: append([]predicate.StarDict{}, sdq.predicates...),
		// clone intermediate query.
		sql:    sdq.sql.Clone(),
		path:   sdq.path,
		unique: sdq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Word string `json:"word,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.StarDict.Query().
//		GroupBy(stardict.FieldWord).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (sdq *StarDictQuery) GroupBy(field string, fields ...string) *StarDictGroupBy {
	group := &StarDictGroupBy{config: sdq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := sdq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return sdq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Word string `json:"word,omitempty"`
//	}
//
//	client.StarDict.Query().
//		Select(stardict.FieldWord).
//		Scan(ctx, &v)
//
func (sdq *StarDictQuery) Select(fields ...string) *StarDictSelect {
	sdq.fields = append(sdq.fields, fields...)
	return &StarDictSelect{StarDictQuery: sdq}
}

func (sdq *StarDictQuery) prepareQuery(ctx context.Context) error {
	for _, f := range sdq.fields {
		if !stardict.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sdq.path != nil {
		prev, err := sdq.path(ctx)
		if err != nil {
			return err
		}
		sdq.sql = prev
	}
	return nil
}

func (sdq *StarDictQuery) sqlAll(ctx context.Context) ([]*StarDict, error) {
	var (
		nodes = []*StarDict{}
		_spec = sdq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &StarDict{config: sdq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, sdq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (sdq *StarDictQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sdq.querySpec()
	_spec.Node.Columns = sdq.fields
	if len(sdq.fields) > 0 {
		_spec.Unique = sdq.unique != nil && *sdq.unique
	}
	return sqlgraph.CountNodes(ctx, sdq.driver, _spec)
}

func (sdq *StarDictQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := sdq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (sdq *StarDictQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   stardict.Table,
			Columns: stardict.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: stardict.FieldID,
			},
		},
		From:   sdq.sql,
		Unique: true,
	}
	if unique := sdq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := sdq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, stardict.FieldID)
		for i := range fields {
			if fields[i] != stardict.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := sdq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sdq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sdq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sdq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sdq *StarDictQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sdq.driver.Dialect())
	t1 := builder.Table(stardict.Table)
	columns := sdq.fields
	if len(columns) == 0 {
		columns = stardict.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sdq.sql != nil {
		selector = sdq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sdq.unique != nil && *sdq.unique {
		selector.Distinct()
	}
	for _, p := range sdq.predicates {
		p(selector)
	}
	for _, p := range sdq.order {
		p(selector)
	}
	if offset := sdq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sdq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// StarDictGroupBy is the group-by builder for StarDict entities.
type StarDictGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sdgb *StarDictGroupBy) Aggregate(fns ...AggregateFunc) *StarDictGroupBy {
	sdgb.fns = append(sdgb.fns, fns...)
	return sdgb
}

// Scan applies the group-by query and scans the result into the given value.
func (sdgb *StarDictGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := sdgb.path(ctx)
	if err != nil {
		return err
	}
	sdgb.sql = query
	return sdgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (sdgb *StarDictGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := sdgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (sdgb *StarDictGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(sdgb.fields) > 1 {
		return nil, errors.New("ent: StarDictGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := sdgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (sdgb *StarDictGroupBy) StringsX(ctx context.Context) []string {
	v, err := sdgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (sdgb *StarDictGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = sdgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{stardict.Label}
	default:
		err = fmt.Errorf("ent: StarDictGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (sdgb *StarDictGroupBy) StringX(ctx context.Context) string {
	v, err := sdgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (sdgb *StarDictGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(sdgb.fields) > 1 {
		return nil, errors.New("ent: StarDictGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := sdgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (sdgb *StarDictGroupBy) IntsX(ctx context.Context) []int {
	v, err := sdgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (sdgb *StarDictGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = sdgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{stardict.Label}
	default:
		err = fmt.Errorf("ent: StarDictGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (sdgb *StarDictGroupBy) IntX(ctx context.Context) int {
	v, err := sdgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (sdgb *StarDictGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(sdgb.fields) > 1 {
		return nil, errors.New("ent: StarDictGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := sdgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (sdgb *StarDictGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := sdgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (sdgb *StarDictGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = sdgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{stardict.Label}
	default:
		err = fmt.Errorf("ent: StarDictGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (sdgb *StarDictGroupBy) Float64X(ctx context.Context) float64 {
	v, err := sdgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (sdgb *StarDictGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(sdgb.fields) > 1 {
		return nil, errors.New("ent: StarDictGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := sdgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (sdgb *StarDictGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := sdgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (sdgb *StarDictGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = sdgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{stardict.Label}
	default:
		err = fmt.Errorf("ent: StarDictGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (sdgb *StarDictGroupBy) BoolX(ctx context.Context) bool {
	v, err := sdgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (sdgb *StarDictGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range sdgb.fields {
		if !stardict.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := sdgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sdgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (sdgb *StarDictGroupBy) sqlQuery() *sql.Selector {
	selector := sdgb.sql.Select()
	aggregation := make([]string, 0, len(sdgb.fns))
	for _, fn := range sdgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(sdgb.fields)+len(sdgb.fns))
		for _, f := range sdgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(sdgb.fields...)...)
}

// StarDictSelect is the builder for selecting fields of StarDict entities.
type StarDictSelect struct {
	*StarDictQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (sds *StarDictSelect) Scan(ctx context.Context, v interface{}) error {
	if err := sds.prepareQuery(ctx); err != nil {
		return err
	}
	sds.sql = sds.StarDictQuery.sqlQuery(ctx)
	return sds.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (sds *StarDictSelect) ScanX(ctx context.Context, v interface{}) {
	if err := sds.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (sds *StarDictSelect) Strings(ctx context.Context) ([]string, error) {
	if len(sds.fields) > 1 {
		return nil, errors.New("ent: StarDictSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := sds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (sds *StarDictSelect) StringsX(ctx context.Context) []string {
	v, err := sds.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (sds *StarDictSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = sds.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{stardict.Label}
	default:
		err = fmt.Errorf("ent: StarDictSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (sds *StarDictSelect) StringX(ctx context.Context) string {
	v, err := sds.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (sds *StarDictSelect) Ints(ctx context.Context) ([]int, error) {
	if len(sds.fields) > 1 {
		return nil, errors.New("ent: StarDictSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := sds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (sds *StarDictSelect) IntsX(ctx context.Context) []int {
	v, err := sds.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (sds *StarDictSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = sds.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{stardict.Label}
	default:
		err = fmt.Errorf("ent: StarDictSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (sds *StarDictSelect) IntX(ctx context.Context) int {
	v, err := sds.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (sds *StarDictSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(sds.fields) > 1 {
		return nil, errors.New("ent: StarDictSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := sds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (sds *StarDictSelect) Float64sX(ctx context.Context) []float64 {
	v, err := sds.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (sds *StarDictSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = sds.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{stardict.Label}
	default:
		err = fmt.Errorf("ent: StarDictSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (sds *StarDictSelect) Float64X(ctx context.Context) float64 {
	v, err := sds.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (sds *StarDictSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(sds.fields) > 1 {
		return nil, errors.New("ent: StarDictSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := sds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (sds *StarDictSelect) BoolsX(ctx context.Context) []bool {
	v, err := sds.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (sds *StarDictSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = sds.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{stardict.Label}
	default:
		err = fmt.Errorf("ent: StarDictSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (sds *StarDictSelect) BoolX(ctx context.Context) bool {
	v, err := sds.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (sds *StarDictSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := sds.sql.Query()
	if err := sds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
