// Code generated by entc, DO NOT EDIT.

package words

import (
	"time"
)

const (
	// Label holds the string label denoting the words type in the database.
	Label = "words"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldWord holds the string denoting the word field in the database.
	FieldWord = "word"
	// FieldExplain holds the string denoting the explain field in the database.
	FieldExplain = "explain"
	// FieldPhonetic holds the string denoting the phonetic field in the database.
	FieldPhonetic = "phonetic"
	// FieldFrequency holds the string denoting the frequency field in the database.
	FieldFrequency = "frequency"
	// FieldLastShowTime holds the string denoting the last_show_time field in the database.
	FieldLastShowTime = "last_show_time"
	// FieldIsHide holds the string denoting the is_hide field in the database.
	FieldIsHide = "is_hide"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldDeleteTime holds the string denoting the delete_time field in the database.
	FieldDeleteTime = "delete_time"
	// FieldIsDelete holds the string denoting the is_delete field in the database.
	FieldIsDelete = "is_delete"
	// Table holds the table name of the words in the database.
	Table = "words"
)

// Columns holds all SQL columns for words fields.
var Columns = []string{
	FieldID,
	FieldWord,
	FieldExplain,
	FieldPhonetic,
	FieldFrequency,
	FieldLastShowTime,
	FieldIsHide,
	FieldCreateTime,
	FieldDeleteTime,
	FieldIsDelete,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// WordValidator is a validator for the "word" field. It is called by the builders before save.
	WordValidator func(string) error
	// DefaultExplain holds the default value on creation for the "explain" field.
	DefaultExplain string
	// DefaultPhonetic holds the default value on creation for the "phonetic" field.
	DefaultPhonetic string
	// DefaultFrequency holds the default value on creation for the "frequency" field.
	DefaultFrequency int
	// FrequencyValidator is a validator for the "frequency" field. It is called by the builders before save.
	FrequencyValidator func(int) error
	// DefaultLastShowTime holds the default value on creation for the "last_show_time" field.
	DefaultLastShowTime func() time.Time
	// DefaultIsHide holds the default value on creation for the "is_hide" field.
	DefaultIsHide bool
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultDeleteTime holds the default value on creation for the "delete_time" field.
	DefaultDeleteTime func() time.Time
	// DefaultIsDelete holds the default value on creation for the "is_delete" field.
	DefaultIsDelete bool
)
